apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  admin_password_secret: awx-admin-password
  secret_key_secret: custom-awx-secret-key
  service_type: ClusterIP
  #loadbalancer_protocol: http
  #loadbalancer_port: 80
  service_annotations: |
    environment: testing
  service_labels: |
    environment: testing