---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  awx.conf: |
    upstream awx {
     server awx-demo-service.awx.svc.cluster.local:80;
    }
    server{ 
      listen 3000;
      location / {
        proxy_pass http://awx;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
      }
    }
    
 
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awx
  template:
    metadata:
      labels:
        app: awx
    spec:
      containers:
      - name: awx-nginx
        image: nginx
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: awxconfig
            mountPath: /etc/nginx/conf.d 
            readOnly: true
            
      volumes:
          - name: awxconfig
            configMap:
              name: nginx-conf
              items:
              - key: awx.conf 
                path: awx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: awx-nginx-service
  namespace: default
  labels:
    app: awx
spec:
  type: ClusterIP
  selector:
    app: awx
  ports:
    - name: awx
      protocol: TCP
      port: 5000
      targetPort: 3000